Changelog
=========

O.3.3:
    * Fix missing require

O.3.2:
    * Better support for local dtd. It can a relative path from the XML filename.
    * Bug fix: the EMPTY tags are support correctly!

O.3.1:
    * Render the text element as HTML format when exporting in XML (no autoclose tag)
    * Bug fix: make sure we add empty text element in the HTML form

O.3:
    * Rewrite the core of the code
    * Better performance to generate the HTML
    * Bug fix

O.2:
    * Update the project architecture
    * Be able to access to the element properties like a dict
    * Add functions to easily update or create XML file
    * Fix missing README file in the package

O.1:
    * Initial version: package to manipulate XML file and create HTML forms.
